all: add2PB findPhone

add2PB: add2PB.cpp
	g++ -o add2PB add2PB.cpp

findPhone: findPhone.cpp
	g++ -o findPhone findPhone.cpp

clean:
	rm -f add2PB findPhone


# ./add2PB "John Doe" "123-456-7890"
# ./findPhone "John Doe"
